version: '3.9'
services:
  mailhog:
    image: 'mailhog/mailhog'
    ports:
      - '1025:1025'
      - '8025:8025'
  react:
    build: ./client
    ports:
      - 3000:3000
  api:
    build: ./api
    ports:
      - 8000:80
    volumes:
      - files:/files
  docking-service:
    build: ./DockingService
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - files:/files
  docking-prepper-service:
    build: ./DockingPrepperService
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - files:/files
  fasta-service:
    build: ./FASTAService
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - files:/files
  mail-service:
    build: ./MailService
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  files:
